##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, float oning:0, onworkspace:w[tv1]
# windowrule = rounding 0, float oning:0, onworkspace:w[tv1]
# windowrule = bordersize 0, float oning:0, onworkspace:f[1]
# windowrule = rounding 0, float oning:0, onworkspace:f[1]
# windowrulev2 = opacity 0.8 0.8,match:class ^(org.gnome.Nautilus)$
windowrule = opacity 0.80 0.70,match:class ristretto
layerrule = blur on,match:namespace ristretto
windowrule = opacity 0.80 0.70,match:class lollypop
layerrule = blur on,match:namespace ristretto
layerrule = blur on,match:namespace hyprpanel

#for kitty opacity
windowrule = opacity 1.2 1.2,match:class kitty

# window rule for waypaper float oning
windowrule = float on,match:class waypaper,match:title Waypaper
windowrule = float on,match:class chromium,match:title This page wants to save

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on,match:class *,match:title *,match:xwayland true,match:float true,match:fullscreen true,match:pin on
